# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NetworkContinuity
                                 A QGIS plugin
 This plugin deduces natural continuity and hierarchy of street networks.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-23
        copyright            : (C) 2020 by Pratyush Tripathy
        email                : pratkrt@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NetworkContinuity class from file NetworkContinuity.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .coins import NetworkContinuity
    return NetworkContinuity(iface)
